### ISSUE TITLE
Window Heating and climatisation

### ISSUE THREAD

**Issue by Libar19** [marn06/homebridge-vw#4]
Hi, it's possible to separate the window heating and climatisation ? 
thank you for this plugin

**Comment by marn06** [comment]
Hi @Libar19 
I have released a new version 1.0.11 that adds the combineHeating property, that when set to false shows a climatisation fan and a window-heating fan. I also added a showBatteryTile that creates a thermostat to display the battery percentage, it's unfortunately the best solution I could find, due to missing functionality in Homekit.
Hope it works for you.

**Comment by Libar19** [comment]
It's perfect For me!
Thank's you very much
